# Generated by Django 3.2 on 2021-05-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('additional_information', models.TextField()),
                ('acquisition_date', models.BigIntegerField(default=1620572516471.315)),
                ('acquisition_value', models.BigIntegerField()),
            ],
        ),
    ]
