# Generated by Django 3.2 on 2021-05-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('join_date', models.BigIntegerField(default=1620572516453.6382)),
                ('password', models.TextField()),
            ],
        ),
    ]
